import enum


class AuditAction(enum.StrEnum):
    # Authentication & Session
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    AUTH_SIGNUP = "AUTH_SIGNUP"
    AUTH_PASSWORD_CHANGED = "AUTH_PASSWORD_CHANGED"

    # User & Account Management
    USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_DELETED = "USER_DELETED"

    # School Management
    SCHOOL_CREATED = "SCHOOL_CREATED"
    SCHOOL_UPDATED = "SCHOOL_UPDATED"
    SCHOOL_DELETED = "SCHOOL_DELETED"

    # School Class Management
    CLASS_CREATED = "CLASS_CREATED"
    CLASS_UPDATED = "CLASS_UPDATED"
    CLASS_DELETED = "CLASS_DELETED"

    # Membership & Join Requests
    STUDENT_JOIN_REQUEST_SUBMITTED = "STUDENT_JOIN_REQUEST_SUBMITTED"
    STUDENT_JOIN_REQUEST_APPROVED = "STUDENT_JOIN_REQUEST_APPROVED"
    STUDENT_JOIN_REQUEST_REJECTED = "STUDENT_JOIN_REQUEST_REJECTED"

    TEACHER_SCHOOL_JOIN_REQUEST_SUBMITTED = "TEACHER_SCHOOL_JOIN_REQUEST_SUBMITTED"
    TEACHER_SCHOOL_JOIN_REQUEST_APPROVED = "TEACHER_SCHOOL_JOIN_REQUEST_APPROVED"
    TEACHER_SCHOOL_JOIN_REQUEST_REJECTED = "TEACHER_SCHOOL_JOIN_REQUEST_REJECTED"

    TEACHER_REQUEST_SUBMITTED = "TEACHER_REQUEST_SUBMITTED"
    TEACHER_REQUEST_APPROVED = "TEACHER_REQUEST_APPROVED"
    TEACHER_REQUEST_REJECTED = "TEACHER_REQUEST_REJECTED"

    TEACHER_CLASS_JOIN_REQUEST_SUBMITTED = "TEACHER_CLASS_JOIN_REQUEST_SUBMITTED"
    TEACHER_CLASS_JOIN_REQUEST_APPROVED = "TEACHER_CLASS_JOIN_REQUEST_APPROVED"
    TEACHER_CLASS_JOIN_REQUEST_REJECTED = "TEACHER_CLASS_JOIN_REQUEST_REJECTED"

    # Teacher class assignment
    TEACHER_CLASS_ASSIGNED = "TEACHER_CLASS_ASSIGNED"
    TEACHER_CLASS_REMOVED = "TEACHER_CLASS_REMOVED"

    # Exam Management
    EXAM_CREATED = "EXAM_CREATED"
    EXAM_UPDATED = "EXAM_UPDATED"
    EXAM_DELETED = "EXAM_DELETED"
    EXAM_PUBLISHED = "EXAM_PUBLISHED"
    EXAM_RESULTS_RELEASED = "EXAM_RESULTS_RELEASED"

    # Section Management
    SECTION_CREATED = "SECTION_CREATED"
    SECTION_UPDATED = "SECTION_UPDATED"
    SECTION_DELETED = "SECTION_DELETED"

    # Question Management
    QUESTION_CREATED = "QUESTION_CREATED"
    QUESTION_UPDATED = "QUESTION_UPDATED"
    QUESTION_DELETED = "QUESTION_DELETED"

    # Exam Taking & Proctoring
    EXAM_STARTED = "EXAM_STARTED"
    EXAM_ATTEMPT_STARTED = "EXAM_ATTEMPT_STARTED"
    EXAM_ANSWER_SAVED = "EXAM_ANSWER_SAVED"
    EXAM_SUBMITTED = "EXAM_SUBMITTED"
    EXAM_AUTO_SUBMITTED = "EXAM_AUTO_SUBMITTED"
    PROCTORING_VIOLATION = "PROCTORING_VIOLATION"

    # Grading & Scores
    MANUAL_GRADE_UPDATED = "MANUAL_GRADE_UPDATED"


class AuditResourceType(enum.StrEnum):
    AUTH = "AUTH"
    USER = "USER"
    SCHOOL = "SCHOOL"
    SCHOOL_CLASS = "SCHOOL_CLASS"
    JOIN_REQUEST = "JOIN_REQUEST"
    TEACHER_REQUEST = "TEACHER_REQUEST"
    TEACHER_CLASS = "TEACHER_CLASS"
    EXAM = "EXAM"
    SECTION = "SECTION"
    EXAM_SECTION = "EXAM_SECTION"
    QUESTION = "QUESTION"
    STUDENT_EXAM = "STUDENT_EXAM"
    EXAM_ATTEMPT = "EXAM_ATTEMPT"
    PROCTORING = "PROCTORING"
    GRADING = "GRADING"
