"""Seed data fixtures containing realistic configurations for ExamArena testing."""

import json
from datetime import UTC, datetime, timedelta

from app.core.models import ExamType, QuestionType, Subject

SCHOOL_FIXTURE = {
    "name": "Oakridge International Academy",
    "schoolCode": "OAK101",
    "address": "Plot 42, Knowledge Boulevard, Sector 62",
    "city": "New Delhi",
    "state": "Delhi",
    "country": "India",
    "pincode": "110001",
    "email": "admin@oakridge-academy.edu",
    "website": "https://oakridge-academy.edu",
    "phoneNo": "+91 11 2893 4400",
}

USERS_FIXTURES = {
    "admin": {
        "name": "System Administrator",
        "email": "admin@gmail.com",
        "phone_no": "9811000000",
        "dob": datetime(1980, 1, 15, tzinfo=UTC),
    },
    "principal": {
        "name": "Dr. Evelyn Reed",
        "email": "principal@gmail.com",
        "phone_no": "9811234567",
        "dob": datetime(1976, 4, 12, tzinfo=UTC),
        "qualification": json.dumps(["PHD", "MASTERS"]),
        "experience": 22,
        "department": "School Administration",
        "subjects": json.dumps(["SCIENCE", "LITERATURE"]),
    },
    "teacher1": {
        "name": "Prof. Marcus Brody",
        "email": "teacher@gmail.com",
        "phone_no": "9822345678",
        "dob": datetime(1985, 8, 24, tzinfo=UTC),
        "qualification": json.dumps(["MASTERS", "BACHELORS_WITH_HONORS"]),
        "experience": 10,
        "department": "Physical Sciences",
        "subjects": json.dumps(["SCIENCE"]),
    },
    "teacher2": {
        "name": "Dr. Sarah Jenkins",
        "email": "teacher.math@gmail.com",
        "phone_no": "9833456789",
        "dob": datetime(1988, 11, 15, tzinfo=UTC),
        "qualification": json.dumps(["PHD", "MASTERS"]),
        "experience": 8,
        "department": "Mathematics",
        "subjects": json.dumps(["MATHS"]),
    },
}

CLASSES_FIXTURES = [
    {
        "name": "Class 10",
        "year": "2024",
        "section": "A",
        "joinCode": "CLS10A24",
        "classTeacherKey": "teacher1",
        "nextRollNo": 1005,
    },
    {
        "name": "Class 12",
        "year": "2024",
        "section": "B",
        "joinCode": "CLS12B24",
        "classTeacherKey": "teacher2",
        "nextRollNo": 1205,
    },
]

STUDENTS_FIXTURES = [
    {
        "email": "student@gmail.com",
        "name": "Alex Morgan",
        "dob": datetime(2008, 6, 18, tzinfo=UTC),
        "phone": "9844567890",
        "class_name": "Class 10",
        "class_section": "A",
        "rollNo": "1001",
        "parentName": "Robert Morgan",
        "parentEmail": "robert.morgan@gmail.com",
        "fatherName": "Robert Morgan",
        "fatherPhone": "9844567891",
        "motherName": "Elena Morgan",
        "motherPhone": "9844567892",
    },
    {
        "email": "emma.student@gmail.com",
        "name": "Emma Watson",
        "dob": datetime(2008, 9, 22, tzinfo=UTC),
        "phone": "9855678901",
        "class_name": "Class 10",
        "class_section": "A",
        "rollNo": "1002",
        "parentName": "Christopher Watson",
        "parentEmail": "chris.watson@gmail.com",
        "fatherName": "Christopher Watson",
        "fatherPhone": "9855678902",
        "motherName": "Jacqueline Watson",
        "motherPhone": "9855678903",
    },
    {
        "email": "liam.student@gmail.com",
        "name": "Liam Davies",
        "dob": datetime(2006, 3, 14, tzinfo=UTC),
        "phone": "9866789012",
        "class_name": "Class 12",
        "class_section": "B",
        "rollNo": "1201",
        "parentName": "David Davies",
        "parentEmail": "david.davies@gmail.com",
        "fatherName": "David Davies",
        "fatherPhone": "9866789013",
        "motherName": "Hannah Davies",
        "motherPhone": "9866789014",
    },
    {
        "email": "sophia.student@gmail.com",
        "name": "Sophia Chen",
        "dob": datetime(2006, 11, 5, tzinfo=UTC),
        "phone": "9877890123",
        "class_name": "Class 12",
        "class_section": "B",
        "rollNo": "1202",
        "parentName": "Wei Chen",
        "parentEmail": "wei.chen@gmail.com",
        "fatherName": "Wei Chen",
        "fatherPhone": "9877890124",
        "motherName": "Mei-Ling Chen",
        "motherPhone": "9877890125",
    },
]

EXAMS_FIXTURES = [
    {
        "key": "exam1",
        "teacherKey": "teacher1",
        "name": "CBSE Class 10 Science: Force, Work & Chemical Bonding",
        "description": "Comprehensive mid-term evaluation covering Newtonian mechanics, energy conservation principles, and chemical bonding.",
        "scheduledAt": datetime.now(UTC) - timedelta(days=5),
        "duration": 45,
        "maxMarks": 30,
        "instructions": "1. Read all questions carefully.\n2. Section A has MCQs (2 marks each).\n3. Section B has True/False questions (2 marks each).\n4. Section C has Short Answer analytical questions (5 marks each).",
        "isPublished": True,
        "isPublic": True,
        "isResultsReleased": True,
        "subject": Subject.SCIENCE,
        "type": ExamType.MIDTERM,
        "sections": [
            {
                "name": "Section A",
                "description": "Multiple Choice Questions",
                "questionType": QuestionType.MULTIPLE_CHOICE,
                "marksPerQuestion": 2,
                "sortOrder": 1,
            },
            {
                "name": "Section B",
                "description": "True or False Conceptual Verification",
                "questionType": QuestionType.TRUE_FALSE,
                "marksPerQuestion": 2,
                "sortOrder": 2,
            },
            {
                "name": "Section C",
                "description": "Short Answer & Problem Solving",
                "questionType": QuestionType.SHORT_ANSWER,
                "marksPerQuestion": 5,
                "sortOrder": 3,
            },
        ],
        "questions": [
            {
                "section": "Section A",
                "qNum": 1,
                "text": "What is the SI unit of gravitational potential energy and work done?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "Work and all forms of energy are measured in Joules (J) in the SI system.",
                "options": [
                    ("Newton (N)", False),
                    ("Joule (J)", True),
                    ("Watt (W)", False),
                    ("Pascal (Pa)", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 2,
                "text": "According to Newton's Second Law (F = ma), what happens to the acceleration if the net force acting on an object is doubled while mass remains constant?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "Acceleration is directly proportional to net force. Doubling the force doubles the acceleration.",
                "options": [
                    ("Halved", False),
                    ("Remains unchanged", False),
                    ("Doubled", True),
                    ("Quadrupled", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 3,
                "text": "Which chemical element has the highest electronegativity value on the Pauling scale?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "Fluorine is the most electronegative element with a value of 3.98.",
                "options": [
                    ("Oxygen", False),
                    ("Chlorine", False),
                    ("Fluorine", True),
                    ("Nitrogen", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 4,
                "text": "A 2.0 kg toy car moves at a steady velocity of 5.0 m/s. What is its kinetic energy?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "KE = 0.5 * m * v^2 = 0.5 * 2.0 * 25 = 25 Joules.",
                "options": [
                    ("10 Joules", False),
                    ("25 Joules", True),
                    ("50 Joules", False),
                    ("100 Joules", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 5,
                "text": "What type of chemical bond is formed when valence electrons are shared equally between two identical non-metallic atoms?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "Equal sharing between identical atoms creates a nonpolar covalent bond.",
                "options": [
                    ("Nonpolar Covalent Bond", True),
                    ("Polar Covalent Bond", False),
                    ("Ionic Bond", False),
                    ("Coordinate Bond", False),
                ],
            },
            {
                "section": "Section B",
                "qNum": 6,
                "text": "Sound waves can propagate through a vacuum because they are electromagnetic waves.",
                "type": QuestionType.TRUE_FALSE,
                "marks": 2,
                "explanation": "Sound is a mechanical wave that requires a material medium to propagate; it cannot travel in a vacuum.",
                "options": [
                    ("True", False),
                    ("False", True),
                ],
            },
            {
                "section": "Section B",
                "qNum": 7,
                "text": "In an isolated physical system, total linear momentum is strictly conserved during all collisions.",
                "type": QuestionType.TRUE_FALSE,
                "marks": 2,
                "explanation": "By Newton's third law and momentum conservation, total momentum remains unchanged without external forces.",
                "options": [
                    ("True", True),
                    ("False", False),
                ],
            },
            {
                "section": "Section B",
                "qNum": 8,
                "text": "An aqueous solution with a pH value of 3.5 at 25°C is classified as basic.",
                "type": QuestionType.TRUE_FALSE,
                "marks": 2,
                "explanation": "Solutions with pH < 7 are acidic. 3.5 is strongly acidic.",
                "options": [
                    ("True", False),
                    ("False", True),
                ],
            },
            {
                "section": "Section C",
                "qNum": 9,
                "text": "Distinguish clearly between speed and velocity. Provide a practical real-world example explaining why direction is essential for velocity.",
                "type": QuestionType.SHORT_ANSWER,
                "marks": 7,
                "wordLimit": 150,
                "explanation": "Speed is a scalar quantity measuring rate of distance, whereas velocity is a vector combining speed and direction (e.g. 80 km/h North vs South).",
                "options": [],
            },
            {
                "section": "Section C",
                "qNum": 10,
                "text": "State Boyle's Law of ideal gases and write its standard algebraic equation for a fixed mass at constant temperature.",
                "type": QuestionType.SHORT_ANSWER,
                "marks": 7,
                "wordLimit": 100,
                "explanation": "Boyle's Law states that at constant temperature, pressure is inversely proportional to volume: P1 * V1 = P2 * V2.",
                "options": [],
            },
        ],
    },
    {
        "key": "exam2",
        "teacherKey": "teacher2",
        "name": "Senior Mathematics: Matrices, Vector Algebra & Calculus",
        "description": "Advanced board preparation examination covering matrix operations, derivatives, vector scalar products, and local extrema.",
        "scheduledAt": datetime.now(UTC) - timedelta(days=3),
        "duration": 60,
        "maxMarks": 35,
        "instructions": "1. Show all necessary algebraic steps.\n2. In Section B (Multiple Select), select all correct statements.\n3. Section C requires full calculus proofs.",
        "isPublished": True,
        "isPublic": True,
        "isResultsReleased": True,
        "subject": Subject.MATHS,
        "type": ExamType.FINAL,
        "sections": [
            {
                "name": "Section A",
                "description": "Multiple Choice Questions",
                "questionType": QuestionType.MULTIPLE_CHOICE,
                "marksPerQuestion": 3,
                "sortOrder": 1,
            },
            {
                "name": "Section B",
                "description": "Multi-Select Concept Checks",
                "questionType": QuestionType.MULTIPLE_SELECT,
                "marksPerQuestion": 5,
                "sortOrder": 2,
            },
            {
                "name": "Section C",
                "description": "Calculus & Analytical Problems",
                "questionType": QuestionType.SHORT_ANSWER,
                "marksPerQuestion": 10,
                "sortOrder": 3,
            },
        ],
        "questions": [
            {
                "section": "Section A",
                "qNum": 1,
                "text": "What is the determinant of the 2x2 matrix A = [[3, 5], [2, 4]]?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 3,
                "explanation": "det(A) = (3 * 4) - (5 * 2) = 12 - 10 = 2.",
                "options": [
                    ("2", True),
                    ("7", False),
                    ("14", False),
                    ("22", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 2,
                "text": "Find the first derivative of f(x) = e^(3x) with respect to x.",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 3,
                "explanation": "By chain rule, d/dx[e^(3x)] = 3 * e^(3x).",
                "options": [
                    ("e^(3x)", False),
                    ("3 * e^(3x)", True),
                    ("(1/3) * e^(3x)", False),
                    ("3x * e^(3x-1)", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 3,
                "text": "Calculate the dot product of vectors u = (2, 3, -1) and v = (4, -2, 5).",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 3,
                "explanation": "u · v = (2*4) + (3*-2) + (-1*5) = 8 - 6 - 5 = -3.",
                "options": [
                    ("-3", True),
                    ("5", False),
                    ("7", False),
                    ("13", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 4,
                "text": "If the roots of the quadratic equation x^2 - 7x + 12 = 0 are p and q, what is the product p * q?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 3,
                "explanation": "In ax^2 + bx + c = 0, product of roots is c/a = 12/1 = 12.",
                "options": [
                    ("7", False),
                    ("-7", False),
                    ("12", True),
                    ("-12", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 5,
                "text": "Evaluate the indefinite integral ∫ (2x + 5) dx.",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 3,
                "explanation": "∫ (2x + 5) dx = x^2 + 5x + C.",
                "options": [
                    ("x^2 + 5x + C", True),
                    ("2x^2 + 5x + C", False),
                    ("x^2 + C", False),
                    ("2 + C", False),
                ],
            },
            {
                "section": "Section B",
                "qNum": 6,
                "text": "Which of the following functions are continuous everywhere on the real number set ℝ?",
                "type": QuestionType.MULTIPLE_SELECT,
                "marks": 5,
                "explanation": "Sine, polynomials, and absolute value functions are continuous everywhere. 1/x is discontinuous at x=0.",
                "options": [
                    ("f(x) = sin(x)", True),
                    ("f(x) = x^3 - 4x + 1", True),
                    ("f(x) = 1 / x", False),
                    ("f(x) = |x|", True),
                ],
            },
            {
                "section": "Section B",
                "qNum": 7,
                "text": "Select all square matrices below that are singular (determinant equals zero).",
                "type": QuestionType.MULTIPLE_SELECT,
                "marks": 5,
                "explanation": "A matrix is singular if its determinant is zero. det([[2,4],[1,2]])=0 and det([[6,-3],[-4,2]])=12-12=0.",
                "options": [
                    ("[[2, 4], [1, 2]]", True),
                    ("[[3, 0], [0, 5]]", False),
                    ("[[6, -3], [-4, 2]]", True),
                    ("[[1, 0], [0, 1]]", False),
                ],
            },
            {
                "section": "Section C",
                "qNum": 8,
                "text": "Determine the critical point of f(x) = 2x^2 - 8x + 6. Use the second derivative test to classify it as a local minimum or maximum, and calculate its coordinates.",
                "type": QuestionType.SHORT_ANSWER,
                "marks": 10,
                "wordLimit": 150,
                "explanation": "f'(x) = 4x - 8 = 0 => x = 2. f''(x) = 4 > 0 => local minimum at (2, -2).",
                "options": [],
            },
        ],
    },
    {
        "key": "exam3",
        "teacherKey": "teacher1",
        "name": "Cellular Biology & Genetics Periodic Quiz",
        "description": "Weekly rapid assessment on organelle functions, Mendelian genetics, and nucleic acids.",
        "scheduledAt": datetime.now(UTC) - timedelta(hours=2),
        "duration": 30,
        "maxMarks": 20,
        "instructions": "10 multiple-choice questions. 2 marks each.",
        "isPublished": True,
        "isPublic": True,
        "isResultsReleased": False,
        "subject": Subject.SCIENCE,
        "type": ExamType.QUIZ,
        "sections": [
            {
                "name": "Section A",
                "description": "Quick Fire Multiple Choice",
                "questionType": QuestionType.MULTIPLE_CHOICE,
                "marksPerQuestion": 2,
                "sortOrder": 1,
            }
        ],
        "questions": [
            {
                "section": "Section A",
                "qNum": 1,
                "text": "Which cellular organelle is universally referred to as the powerhouse of eukaryotic cells?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "Mitochondria generate ATP through cellular respiration.",
                "options": [
                    ("Nucleus", False),
                    ("Mitochondria", True),
                    ("Ribosome", False),
                    ("Golgi apparatus", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 2,
                "text": "What is the fundamental hereditary molecule carrying genetic blueprints in humans?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "DNA stores genetic information.",
                "options": [
                    ("RNA", False),
                    ("DNA", True),
                    ("Protein", False),
                    ("Carbohydrate", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 3,
                "text": "During which stage of mitosis do sister chromatids migrate to opposite poles?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "Anaphase involves chromosome separation.",
                "options": [
                    ("Prophase", False),
                    ("Metaphase", False),
                    ("Anaphase", True),
                    ("Telophase", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 4,
                "text": "What is the standard Mendelian phenotypic ratio in a heterozygous monohybrid cross (Aa x Aa)?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "3 dominant to 1 recessive phenotype.",
                "options": [
                    ("1:1", False),
                    ("3:1", True),
                    ("9:3:3:1", False),
                    ("1:2:1", False),
                ],
            },
            {
                "section": "Section A",
                "qNum": 5,
                "text": "Which enzyme synthesizes mRNA from a DNA template during transcription?",
                "type": QuestionType.MULTIPLE_CHOICE,
                "marks": 2,
                "explanation": "RNA Polymerase catalyzes RNA synthesis.",
                "options": [
                    ("DNA Polymerase", False),
                    ("RNA Polymerase", True),
                    ("Ligase", False),
                    ("Amylase", False),
                ],
            },
        ],
    },
    {
        "key": "exam4",
        "teacherKey": "teacher2",
        "name": "Trigonometry & Coordinate Geometry Challenge",
        "description": "Special challenge problems in trigonometric identities and conic sections.",
        "scheduledAt": datetime.now(UTC) + timedelta(days=2),
        "duration": 40,
        "maxMarks": 25,
        "instructions": "Protected assignment. Enter password provided by Dr. Sarah Jenkins.",
        "isPublished": True,
        "isPublic": False,
        "accessPassword": "TRIG2024",
        "isResultsReleased": False,
        "subject": Subject.MATHS,
        "type": ExamType.ASSIGNMENT,
        "sections": [],
        "questions": [],
    },
]
